### ISSUE TITLE
[Feature request] Support arm64-v8a

### ISSUE THREAD

**Issue by littleGnAl** [microsoft/MapsSDK-Native#12]
**Problem**

The Bing Map SDK only support `armeabi-v7a`, `x86` currently, because our APP support 64-bit devices, so it will cause the crash on the 64-bit devices
```
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxxx/base.apk"],nativeLibraryDirectories=[/data/app/xxxxx/lib/arm64, /data/app/xxx!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libBingMaps.so"
```
actually, we can force our APP to compatible the Bing Map SDK by setting `abiFilters 'armeabi-v7a', 'x86'` but that may let our APP can't upload the Google Play after August 1, 2019 [https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html), and lost performance improvements for the 64-bit devices. 

**Proposal**

Make the Bing Map SDK support `arm64-v8a` architectures.

**Describe alternatives you have considered**

**Screenshots**

**Additional context**

* [https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html)
* [https://developer.android.com/distribute/best-practices/develop/64-bit](https://developer.android.com/distribute/best-practices/develop/64-bit)

**Comment by JuanPapas** [comment]
Thanks @littleGnAl.

We are indeed aware of the deadline and we are working towards releasing a new version with ARM64 support soon.

**Comment by rkoten** [comment]
@littleGnAl ARM64 is now supported as of version 0.2.0.

**Comment by littleGnAl** [comment]
Thank you so much.

**Comment by fergalwasp** [comment]
If anyone lands here from the googlebings... you need to add

ndk.abiFilters 'armeabi-v7a','arm64-v8a'

to your build.gradle or the play store will reject it.
