### ISSUE TITLE
Can't click on marker

### ISSUE THREAD

**Issue by diegoojeda** [microsoft/MapsSDK-Native#14]
Hello,

I just integrated the Bing maps SDK for Android on the app I'm currently working on and can't find a way to detect the click event on the marker icon. 
I already tried to detect the click on the MapView and match it with the existing markers, with no success. 
I also made some experiments with the FlyOut with no success.

Is this functionality implemented?

**Comment by sakthiyuvaraj** [comment]
Hi @diegoojeda 

Currently there is no click event handler in MapIcon.

But, I was able to find the map icon that was clicked with the following code.

```
           mMapView.addOnMapTappedListener(new OnMapTappedListener() {
            @Override
            public boolean onMapTapped(MapTappedEventArgs mapTappedEventArgs) {
                Point position = mapTappedEventArgs.position;
                LinkedList<MapElement> elements = mMapView.findMapElementsAtOffset(position);

                for (MapElement mapElement: elements)
                {
                    if (mapElement instanceof MapIcon) {
                        MapIcon mapIcon = (MapIcon) mapElement;
                         // Do your thing. For example set fly out visibility.
                         // mapIcon.setIsFlyoutVisible(!mapIcon.getIsFlyoutVisible());
                    }
                }

                return false;
            }
        });

```

What issue were you seeing with the Flyout?

**Comment by sakthiyuvaraj** [comment]
I was able to repro the problem you are seeing with flyout. Could you set the flyout visibility after it was added to the layer.

**Comment by diegoojeda** [comment]
Hi,
I finally decided to go for a webview based approach, with the web bing map instead of the native SDK.
