### ISSUE TITLE
iOS Dark mode, demo app

### ISSUE THREAD

**Issue by argiad** [microsoft/MapsSDK-Native#20]
iOS 13, DarkMode
1. UIPickerView background color, to fix -> Main.Storyboard -> Choose the picker -> Attribute Inspector -> Background Color -> System Background

**Comment by JuanPapas** [comment]
Thanks for reporting the issue @argiad. 

The Bing Maps SDK supports custom styling and various built-in styles that can help app developers to provide a good mapping experience to customers that prefer Dark Mode.  Please take a look at our default [MapStyleSheets](https://docs.microsoft.com/en-us/bingmaps/sdk-native/map-control-concepts/map-styles-sheets), and in particular at the dark versions we currently support, like `RoadDark` or `RoadHighContrastDark' (if you need to make the control more accessible as well).

E.g.  You can easily switch the map style in your application by doing:
>```swift
> mapView.setStyleSheet(MSMapStyleSheets.roadDark())
>```

Our goal is to give app developers a way to specify the style sheet and decide what the overall experience should be.  But maybe you are asking for the control to handle the setting automatically?

**Comment by rkoten** [comment]
As of now (merged #26), iOS samples natively handle system UI theme to match map theme.
