### ISSUE TITLE
iOS Demo App, all Modes

### ISSUE THREAD

**Issue by argiad** [microsoft/MapsSDK-Native#21]
MapView's constraints.

Main.storyboard -> MapView -> Size Inspector -> 
1. Align Leading to: Safe Area **1 -> 0**
2.Top Space to Superview : **1 -> 0**
3. Align Trailing to SafeArea: **1 -> 0**
4. Align Bottom **to  Safe Area 1 -> to Superview 0**

**Comment by argiad** [comment]
Same for the Search Demo App

**Comment by JuanPapas** [comment]
Thanks for reporting the issues @argiad, we'll look into that.

**Comment by rkoten** [comment]
Hi @argiad, thanks for bringing us to awareness of layout misalignments, we are now fixing these.
If you have thoughts to add to your original comment, you're welcome to do so.
