### ISSUE TITLE
There is no session key I/F.

### ISSUE THREAD

**Issue by HiroM-telecomsqare** [microsoft/MapsSDK-Native#27]
I cannot find any session key API such as getCredentials() methods  in MapView class in android platform.
'Understanding Bing Maps Transactions' ( https://docs.microsoft.com/en-us/bingmaps/getting-started/bing-maps-dev-center-help/understanding-bing-maps-transactions ) says 'use a session' for saving API cost.
How I can get session key from bing map key in android and ios SDK?

**Comment by rkoten** [comment]
Hi HiroM, great question, let me clarify.

Bing Maps Native SDK takes the responsibility of obtaining a Session ID upon itself, when a MapView is initialized.
Please note that MapServices can be used without a MapView, however in that case every transaction is billable.
