### ISSUE TITLE
How to show all pushin.

### ISSUE THREAD

**Issue by PCGurjar** [microsoft/MapsSDK-Native#29]
How to show all the pushin points, like Bing map in web side , is there any property for this like MapFit.

**Comment by rkoten** [comment]
Hi @PCGurjar,

To display multiple pushpins, add them to a `MapElementLayer`, then add the layer to the `MapView`.
To learn more about pushpin features in Bing Maps Native SDK, please refer to ["Display points of interest on the map"](https://docs.microsoft.com/en-us/bingmaps/sdk-native/map-control-concepts/display-points-of-interest) in official documentation.
