### ISSUE TITLE
Multiple memory leaks

### ISSUE THREAD

**Issue by jim-mcandrew** [microsoft/MapsSDK-Native#36]
<img width="443" alt="Screen Shot 2020-05-06 at 2 37 50 PM" src="https://user-images.githubusercontent.com/6760170/81220599-30d81780-8fa7-11ea-9178-4bf876cfd0da.png">
**Describe the bug**
If I repeatedly set the path property on a MSMapPolyline (10x per second), the app memory slowly increased (1-2mb / sec).

**Steps to reproduce**
1. Create an MSMapPolyline and add it to the map
2. Create a Timer at 0.1s interval
3. Set the path property in the timer callback with a new MSGeopath with an increasing number of positions
4. Watch your memory footprint increase

**Expected behavior**
Either have a way to append positions to the path, or free up the memory from previously updated paths.

**Screenshots**
<img width="443" alt="Screen Shot 2020-05-06 at 2 37 50 PM" src="https://user-images.githubusercontent.com/6760170/81220653-49483200-8fa7-11ea-895b-aa33f82f427e.png">

**Device and SDK information (please complete the following):**
 - OS version: iOS 13.4.1
 - Architecture: arm64
 - Bing Maps SDK version: 1.1.0
 - Language: English
 - Region: US

**Additional context**
None

**Comment by jim-mcandrew** [comment]
Did I little more investigation, and it seems like there is another, possibly more severe memory issue with calling mapView.setScene (10x / sec), especially with camera angles that are near the horizon.

**Comment by JuanPapas** [comment]
Thanks for reporting the issue @jim-mcandrew.
At the moment we are working on fixes for a few other memory leaks. We'll make sure to include these scenarios in our investigation.

**Comment by jim-mcandrew** [comment]
Thanks! We are deciding if we want to release our app as-is, or if we should wait for your fixes. Any idea on the timeframe?

**Comment by JuanPapas** [comment]
We are planning to release the next version at the end of May.  No promises yet, but we'll see if we can accelerate that for next week.

**Comment by JuanPapas** [comment]
Hi @jim-mcandrew, 
We are happy to announce that the latest SDK v1.1.4 includes important improvements around memory usage (peak memory) on iOS.  We are not done by any means, and I want to assure you that we'll continue working on making it better.
