### ISSUE TITLE
OnMapLongClickListener

### ISSUE THREAD

**Issue by m-grzegorczyk** [microsoft/MapsSDK-Native#37]
Hi,

I'm trying to implement long click on map. 

There is a:
- addOnMapTappedListener,
- addOnMapDoubleTappedListener,

but there is no equivalent of addOnMapLongClickListener.

Is there any way to implement OnMapLongClickListener?

**Comment by JuanPapas** [comment]
Hi @m-grzegorczyk, the SDK supports tap & hold gestures with addOnMapHoldingListener.
For more details please see the [Holding](https://docs.microsoft.com/en-us/bingmaps/sdk-native/map-control-api/mapview-class#holding) event in our documentation.
